# Generated by Django 2.1.4 on 2020-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200528_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(null=True, path='/img'),
        ),
    ]
